apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app
        image: multi-user-pdf-qa:latest  # Replace with your Docker image after building
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
        env:
        - name: GEMINI_API_KEY
          value: "your-real-key"  # Placeholder; replace with real key
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"